build:
	g++ -g main.cpp addac_1_gm.cpp ../inv_1/GoldenModel/inv_1_gm.cpp ../flop_1/GoldenModel/flop_1_gm.cpp ../mux_2x1_1/GoldenModel/mux_2x1_1_gm.cpp ../soma_1/GoldenModel/soma_1_gm.cpp -o main.exe -std=c++17

run:
	./main.exe