build:
	g++ -g main.cpp addac_4_gm.cpp ../ADDAC_1/GoldenModel/addac_1_gm.cpp ../ADDAC_1/flop_1/GoldenModel/flop_1_gm.cpp ../ADDAC_1/mux_2x1_1/GoldenModel/mux_2x1_1_gm.cpp ../ADDAC_1/inv_1/GoldenModel/inv_1_gm.cpp ../ADDAC_1/soma_1/GoldenModel/soma_1_gm.cpp -o main.exe

run:
	./main.exe